apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: kafka
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: xxxxx.dkr.ecr.us-east-1.amazonaws.com/funcionario-consumer:latest
        env: 
        - name: KAFKA_TOPIC_NAME 
          value: "topic_test" 
        - name: KAFKA_SERVER 
          value: "my-cluster-kafka-bootstrap"
        - name: KAFKA_PORT 
          value: "9092"
        ports:
        - containerPort: 8001
          protocol: TCP